use db_isisgav;

INSERT INTO CATEGORIA (desc_cat) VALUES ('Guitarra Acustica');

INSERT INTO CATEGORIA (desc_cat) VALUES ('Guitarra Eléctrica');

INSERT INTO CATEGORIA (desc_cat) VALUES ('Guitarra Electroacústica');

INSERT INTO CATEGORIA (desc_cat) VALUES ('Bajo Eléctrico');

INSERT INTO CATEGORIA (desc_cat) VALUES ('Batería');

INSERT INTO forma_pago VALUES (1,'Efectivo'), (2,'Débito/Crédito');

INSERT INTO tipo_usuario (desc_user) values ('Administrador'), ('Vendedor'),('Logística');

INSERT INTO ARTICULO (NOM_ART, MARCA_ART, DESC_ART, ID_CATEGORIA, PRECIO_VENTA)
VALUES ('Guitarra Eléctrica EILCEBGH1', 'Epiphone', 'Les Paul Custom Ebony', 2, 2650);

INSERT INTO ARTICULO (NOM_ART, MARCA_ART, DESC_ART, ID_CATEGORIA, PRECIO_VENTA)
VALUES ('Guitarra Eléctrica EILS5HSNH1', 'Epiphone', 'Les Paul Standard 50s Heritage Cherry Sunburst', 2, 2350);
 
INSERT INTO ARTICULO (NOM_ART, MARCA_ART, DESC_ART, ID_CATEGORIA, PRECIO_VENTA)
VALUES ('Guitarra Electroacústica SA40JU-CFI', 'Stagg', 'Jumbo c/Fishman – Black', 3, 2350);
 
INSERT INTO ARTICULO (NOM_ART, MARCA_ART, DESC_ART, ID_CATEGORIA, PRECIO_VENTA)
VALUES ('Guitarra Electroacústica T5z', 'Taylor', 'Classic Koa', 3, 7950);
 
INSERT INTO ARTICULO (NOM_ART, MARCA_ART, DESC_ART, ID_CATEGORIA, PRECIO_VENTA)
VALUES ('Bajo Eléctrico EBG3EBCH1', 'Epiphone', 'EB-3 Ebony', 4, 1800);
 
INSERT INTO ARTICULO (NOM_ART, MARCA_ART, DESC_ART, ID_CATEGORIA, PRECIO_VENTA)
VALUES ('Bajo Eléctrico V7', 'Sire', 'Marcus Miller V7 Swamp Ash 5 2nd Gen Natural', 4, 3700);

INSERT INTO ARTICULO (NOM_ART, MARCA_ART, DESC_ART, ID_CATEGORIA, PRECIO_VENTA)
VALUES ('Bateria Acústica Cornerstone', 'Dixon', 'Maple Shell Pack 5 Piezas – Natural Gloss', 5, 3550);

INSERT INTO ARTICULO (NOM_ART, MARCA_ART, DESC_ART, ID_CATEGORIA, PRECIO_VENTA)
VALUES ('Bateria Acústica Fuse Limited', 'Dixon', 'Shell Pack 6 Piezas – Magnet', 5, 3100);

INSERT INTO ARTICULO (NOM_ART, MARCA_ART, DESC_ART, ID_CATEGORIA, PRECIO_VENTA)
VALUES ('Bateria Acústica Fuse Maple', 'Dixon', 'Shell Pack 6 Piezas – Gloss Black Burst', 5, 3900);

INSERT INTO EMPLEADO (DNI_EMP, NOM_EMP, APE_EMP, TEL_EMP, CORREO_EMP, DIR_EMP)
VALUES(73112941, 'Andree', 'Maguiña', '997442294', 'AndreeMaguiña@ISISGAV.com.pe', 'Av. Escardo San Miguel');

INSERT INTO EMPLEADO (DNI_EMP, NOM_EMP, APE_EMP, TEL_EMP, CORREO_EMP, DIR_EMP)
VALUES(81479842, 'Eduardo', 'Razuri', '961471859', 'EduardoRazuri@ISISGAV.com.pe', 'Av. Proceres de la Independencia');

INSERT INTO EMPLEADO (DNI_EMP, NOM_EMP, APE_EMP, TEL_EMP, CORREO_EMP, DIR_EMP)
VALUES(74631428, 'Henry', 'Andia', '977263328', 'HenryAndia@ISISGAV.com.pe', 'Av. Las Flores');

INSERT INTO EMPLEADO (DNI_EMP, NOM_EMP, APE_EMP, TEL_EMP, CORREO_EMP, DIR_EMP)
VALUES(48115736, 'Roberto', 'Cedano', '975048268', 'RobertoCedano@ISISGAV.com.pe', 'Av. Tomas Marsano');

INSERT INTO USUARIO (ID_EMPLEADO, USUARIO, PASS) VALUES (1, (SELECT concat(left(NOM_EMP, 1), APE_EMP) FROM EMPLEADO WHERE id_empleado = 1), (SELECT CONCAT(DNI_EMP, left(NOM_EMP,1), LEFT(APE_EMP,1)) FROM EMPLEADO WHERE id_empleado = 1));

INSERT INTO USUARIO (ID_EMPLEADO, USUARIO, PASS)VALUES (2, (SELECT concat(left(NOM_EMP, 1), APE_EMP) FROM EMPLEADO WHERE id_empleado = 2), (SELECT CONCAT(DNI_EMP, left(NOM_EMP,1), LEFT(APE_EMP,1)) FROM EMPLEADO WHERE id_empleado = 2));

INSERT INTO USUARIO (ID_EMPLEADO, USUARIO, PASS)VALUES (3, (SELECT concat(left(NOM_EMP, 1), APE_EMP) FROM EMPLEADO WHERE id_empleado = 3), (SELECT CONCAT(DNI_EMP, left(NOM_EMP,1), LEFT(APE_EMP,1)) FROM EMPLEADO WHERE id_empleado = 3));

INSERT INTO USUARIO (ID_EMPLEADO, USUARIO, PASS) VALUES (4, (SELECT concat(left(NOM_EMP, 1), APE_EMP) FROM EMPLEADO WHERE id_empleado = 4), (SELECT CONCAT(DNI_EMP, left(NOM_EMP,1), LEFT(APE_EMP,1)) FROM EMPLEADO WHERE id_empleado = 4));

INSERT INTO USUARIO_ROLES VALUES (1, 1);
INSERT INTO USUARIO_ROLES VALUES (1, 2);
INSERT INTO USUARIO_ROLES VALUES (2, 1);
INSERT INTO USUARIO_ROLES VALUES (3, 1);
INSERT INTO USUARIO_ROLES VALUES (4, 1);

INSERT INTO PROVEEDOR (RUC_PROV, RAZON_SOCIAL, DIR_PROV, TEL_PROV, CORREO_PROV)
VALUES (20601313490, 'IMPORTACIONES MUSIC PERU S.A.C.', 'AV. DEL PINAR 124 Int. 901', '994488229', 'IMPORTMUSICPERU@GMAIL.COM');

INSERT INTO PROVEEDOR (RUC_PROV, RAZON_SOCIAL, DIR_PROV, TEL_PROV, CORREO_PROV)
VALUES (20544155831, 'IMPORTACIONES PEREZ S.A.C.', 'CAL. JOSE DOMINGO CHOQUEHUANCA 507', '966412874', 'IMPORTPEREZ@GMAIL.COM');

INSERT INTO COMPRA (ID_EMPLEADO, ID_PROVEEDOR, ID_FACTURA, FECHA_COMPRA)
VALUES (1, 1, 'FAC-19712', '2020-11-15');

INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_ARTICULO, CANT_COMPRA, PRECIO_COMPRA) VALUES (1, 1, 15, 2400);
INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_ARTICULO, CANT_COMPRA, PRECIO_COMPRA) VALUES (1, 2, 15, 1800);
INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_ARTICULO, CANT_COMPRA, PRECIO_COMPRA) VALUES (1, 3, 10, 1900);
INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_ARTICULO, CANT_COMPRA, PRECIO_COMPRA) VALUES (1, 4, 5, 6500);
INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_ARTICULO, CANT_COMPRA, PRECIO_COMPRA) VALUES (1, 5, 20, 3300);

INSERT INTO COMPRA (ID_EMPLEADO, ID_PROVEEDOR, ID_FACTURA, FECHA_COMPRA)
VALUES (1, 2, 'FAC-19713', '2020-11-17');

INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_ARTICULO, CANT_COMPRA, PRECIO_COMPRA) VALUES (2, 6, 10, 3300);
INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_ARTICULO, CANT_COMPRA, PRECIO_COMPRA) VALUES (2, 7, 15, 3100);
INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_ARTICULO, CANT_COMPRA, PRECIO_COMPRA) VALUES (2, 8, 10, 2900);
INSERT INTO DETALLE_COMPRA (ID_COMPRA, ID_ARTICULO, CANT_COMPRA, PRECIO_COMPRA) VALUES (2, 9, 10, 1900);

INSERT INTO CLIENTE (TEL_CLI) VALUES ('994226774');
INSERT INTO PERSONA_NATURAL VALUES (1, 'Emilio', 'Carrera', 5411454);

INSERT INTO CLIENTE (DIR_CLI, RUC_CLI, CORREO_CLI, TEL_CLI)
VALUES ('Av. la Fontana Nro. 550 San Cesar de la Molina, La Molina, Lima, Perú',
20297868790, 'compras@usil.edu.pe', '317-1050');
INSERT INTO PERSONA_JURIDICA VALUES (2, 'UNIVERSIDAD SAN IGNACIO DE LOYOLA S.A');

INSERT INTO VENTA (ID_EMPLEADO, ID_CLIENTE, ID_PAGO, FECHA_VENTA, ID_COMPROBANTE_PAGO)
VALUES (1, 1, 1, '2020-11-23', 1);

INSERT INTO DETALLE_VENTA (ID_VENTA, ID_ARTICULO, CANT_VENTA) VALUES (1, 1, 1);
INSERT INTO DETALLE_VENTA (ID_VENTA, ID_ARTICULO, CANT_VENTA) VALUES (1, 2, 2);
INSERT INTO DETALLE_VENTA (ID_VENTA, ID_ARTICULO, CANT_VENTA) VALUES (1, 3, 5);

INSERT INTO VENTA (ID_EMPLEADO, ID_CLIENTE, ID_PAGO, FECHA_VENTA, ID_COMPROBANTE_PAGO)
VALUES (1, 2, 2, '2020-11-23', 2);

INSERT INTO DETALLE_VENTA (ID_VENTA, ID_ARTICULO, CANT_VENTA) VALUES (2, 1, 1);
INSERT INTO DETALLE_VENTA (ID_VENTA, ID_ARTICULO, CANT_VENTA) VALUES (2, 3, 2);
INSERT INTO DETALLE_VENTA (ID_VENTA, ID_ARTICULO, CANT_VENTA) VALUES (2, 5, 1);